from datetime import datetime, timedelta

_now = datetime.utcnow()

MOCK_OFFERS = [
    {"_id": "o1", "hotelId": 1, "hotelName": "Grand Palace Hotel",
     "hotelImage": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600&q=80",
     "hotelLocation": "Dubai Marina, UAE", "rating": 4.8,
     "title": "Weekend Paradise Escape",
     "description": "Enjoy a luxurious weekend getaway with complimentary breakfast and spa access.",
     "discountPercent": 25, "couponCode": "WKND25",
     "validUntil": (_now + timedelta(days=45)).isoformat(),
     "startingPrice": 189, "currency": "USD", "category": "weekend",
     "featured": True, "flashSale": False, "seasonal": False,
     "terms": ["Valid for weekend stays (Fri-Sun)", "Minimum 2 nights required",
               "Cannot be combined with other offers", "Subject to availability"],
     "active": True, "createdAt": (_now - timedelta(days=5)).isoformat(),
     "updatedAt": (_now - timedelta(days=5)).isoformat()},
    {"_id": "o2", "hotelId": 2, "hotelName": "Ocean View Resort",
     "hotelImage": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80",
     "hotelLocation": "Maldives", "rating": 4.9,
     "title": "Family Fun Package",
     "description": "Bring the whole family! Kids stay free with complimentary activities and meals.",
     "discountPercent": 40, "couponCode": "FAMILY40",
     "validUntil": (_now + timedelta(days=60)).isoformat(),
     "startingPrice": 249, "currency": "USD", "category": "family",
     "featured": True, "flashSale": False, "seasonal": False,
     "terms": ["Up to 2 children under 12 stay free", "Meal plan included for kids",
               "Valid for family rooms only", "Advance booking required"],
     "active": True, "createdAt": (_now - timedelta(days=3)).isoformat(),
     "updatedAt": (_now - timedelta(days=3)).isoformat()},
    {"_id": "o3", "hotelId": 3, "hotelName": "Mountain Lodge Retreat",
     "hotelImage": "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80",
     "hotelLocation": "Swiss Alps, Switzerland", "rating": 4.7,
     "title": "Honeymoon Haven",
     "description": "Romantic candlelit dinners, couple's spa treatments, and a mountain-view suite.",
     "discountPercent": 30, "couponCode": "LOVE30",
     "validUntil": (_now + timedelta(days=90)).isoformat(),
     "startingPrice": 329, "currency": "USD", "category": "honeymoon",
     "featured": True, "flashSale": False, "seasonal": False,
     "terms": ["Valid for honeymoon suites only", "Proof of marriage may be required",
               "Includes complimentary champagne", "Spa reservations recommended"],
     "active": True, "createdAt": (_now - timedelta(days=10)).isoformat(),
     "updatedAt": (_now - timedelta(days=10)).isoformat()},
    {"_id": "o4", "hotelId": 4, "hotelName": "Business Suites Tower",
     "hotelImage": "https://images.unsplash.com/photo-1562778612-e1e0cda9915c?w=600&q=80",
     "hotelLocation": "Singapore", "rating": 4.6,
     "title": "Corporate Travel Special",
     "description": "High-speed WiFi, executive lounge access, and meeting room credits included.",
     "discountPercent": 20, "couponCode": "BIZ20",
     "validUntil": (_now + timedelta(days=120)).isoformat(),
     "startingPrice": 159, "currency": "USD", "category": "business",
     "featured": False, "flashSale": True, "seasonal": False,
     "terms": ["Valid for weekday business stays", "Meeting room credits up to $200",
               "Executive lounge access included", "Early check-in available"],
     "active": True, "createdAt": (_now - timedelta(days=1)).isoformat(),
     "updatedAt": (_now - timedelta(days=1)).isoformat()},
    {"_id": "o5", "hotelId": 5, "hotelName": "The Ritz Carlton Suite",
     "hotelImage": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=80",
     "hotelLocation": "Paris, France", "rating": 5.0,
     "title": "Ultimate Luxury Experience",
     "description": "Penthouse suite with butler service, private pool, and chauffeured city tours.",
     "discountPercent": 15, "couponCode": "LUXE15",
     "validUntil": (_now + timedelta(days=30)).isoformat(),
     "startingPrice": 599, "currency": "USD", "category": "luxury",
     "featured": True, "flashSale": False, "seasonal": True,
     "terms": ["Limited to penthouse suites", "Butler service included",
               "City tours subject to availability", "Minimum 3 nights required"],
     "active": True, "createdAt": (_now - timedelta(days=2)).isoformat(),
     "updatedAt": (_now - timedelta(days=2)).isoformat()},
    {"_id": "o6", "hotelId": 6, "hotelName": "Comfort Inn Express",
     "hotelImage": "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&q=80",
     "hotelLocation": "Bangkok, Thailand", "rating": 4.3,
     "title": "Budget Explorer Deal",
     "description": "Clean, comfortable rooms at unbeatable prices. Includes free breakfast and city maps.",
     "discountPercent": 50, "couponCode": "BUDGET50",
     "validUntil": (_now + timedelta(days=75)).isoformat(),
     "startingPrice": 49, "currency": "USD", "category": "budget",
     "featured": False, "flashSale": False, "seasonal": False,
     "terms": ["Valid for standard rooms only", "Breakfast included",
               "Limited-time offer", "Non-refundable"],
     "active": True, "createdAt": (_now - timedelta(days=7)).isoformat(),
     "updatedAt": (_now - timedelta(days=7)).isoformat()},
    {"_id": "o7", "hotelId": 7, "hotelName": "Seaside Villa Resort",
     "hotelImage": "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&q=80",
     "hotelLocation": "Bali, Indonesia", "rating": 4.8,
     "title": "Flash Sale: Beachfront Bliss",
     "description": "Private villa with infinity pool. 24-hour flash sale -- book now!",
     "discountPercent": 55, "couponCode": "FLASH55",
     "validUntil": (_now + timedelta(days=1)).isoformat(),
     "startingPrice": 199, "currency": "USD", "category": "weekend",
     "featured": True, "flashSale": True, "seasonal": False,
     "terms": ["24-hour flash sale", "Non-refundable", "Valid for select villas",
               "Cannot be modified once booked"],
     "active": True, "createdAt": (_now).isoformat(),
     "updatedAt": (_now).isoformat()},
    {"_id": "o8", "hotelId": 8, "hotelName": "Desert Oasis Camp",
     "hotelImage": "https://images.unsplash.com/photo-1528127269322-539801943592?w=600&q=80",
     "hotelLocation": "Rajasthan, India", "rating": 4.5,
     "title": "Seasonal: Monsoon Magic",
     "description": "Experience the desert come alive. Special monsoon rates with camel safari and folk dance.",
     "discountPercent": 35, "couponCode": "MONSOON35",
     "validUntil": (_now + timedelta(days=50)).isoformat(),
     "startingPrice": 89, "currency": "USD", "category": "luxury",
     "featured": False, "flashSale": False, "seasonal": True,
     "terms": ["Valid during monsoon season only", "Camel safari included",
               "Weather-dependent activities", "Minimum 2 nights"],
     "active": True, "createdAt": (_now - timedelta(days=15)).isoformat(),
     "updatedAt": (_now - timedelta(days=15)).isoformat()},
    {"_id": "o9", "hotelId": 9, "hotelName": "Lake View Cottage",
     "hotelImage": "https://images.unsplash.com/photo-1536524214710-1f4e3e4c8c3a?w=600&q=80",
     "hotelLocation": "Lake Garda, Italy", "rating": 4.6,
     "title": "Romantic Couples Retreat",
     "description": "Wine tasting, lakeside dinners, and sunset boat rides for two.",
     "discountPercent": 20, "couponCode": "COUPLE20",
     "validUntil": (_now + timedelta(days=65)).isoformat(),
     "startingPrice": 219, "currency": "USD", "category": "honeymoon",
     "featured": False, "flashSale": False, "seasonal": False,
     "terms": ["Couples only", "Wine tasting included", "Boat ride subject to weather",
               "Advance reservation required"],
     "active": True, "createdAt": (_now - timedelta(days=20)).isoformat(),
     "updatedAt": (_now - timedelta(days=20)).isoformat()},
    {"_id": "o10", "hotelId": 10, "hotelName": "Urban Pod Hotel",
     "hotelImage": "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600&q=80",
     "hotelLocation": "Tokyo, Japan", "rating": 4.2,
     "title": "Solo Traveler Saver",
     "description": "Compact, smart rooms with all essentials. Perfect for the modern solo traveler.",
     "discountPercent": 30, "couponCode": "SOLO30",
     "validUntil": (_now + timedelta(days=35)).isoformat(),
     "startingPrice": 69, "currency": "USD", "category": "budget",
     "featured": False, "flashSale": True, "seasonal": False,
     "terms": ["Valid for single occupancy only", "Smart room amenities included",
               "Access to common areas included", "Self-check-in available"],
     "active": True, "createdAt": (_now - timedelta(days=4)).isoformat(),
     "updatedAt": (_now - timedelta(days=4)).isoformat()},
]


def get_mock_offers(category=None, active=None):
    result = MOCK_OFFERS
    if category and category != "all":
        result = [o for o in result if o["category"] == category]
    if active is not None:
        result = [o for o in result if o["active"] == active]
    return result
