import { FAQData } from "@/types";

export const MOCK_FAQS: FAQData[] = [
  { _id: "f1", question: "How do I cancel my booking?", answer: "You can cancel your booking through your account dashboard under My Bookings. Go to your profile, find the booking you want to cancel, and click the 'Cancel Booking' button. Free cancellation is available up to 48 hours before check-in for most properties. Some non-refundable bookings may not be eligible for cancellation.", category: "Cancellations", popular: true, order: 1, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f2", question: "Is my payment secure?", answer: "Absolutely. LuminaStay uses enterprise-grade 256-bit SSL encryption to protect all transactions. We are PCI-DSS compliant and never store your full payment details. Your payment information is processed directly through trusted payment gateways including Razorpay, Stripe, and PayPal.", category: "Payments", popular: true, order: 2, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f3", question: "Can I modify my reservation?", answer: "Yes, you can modify your reservation dates or room type from your account dashboard. Go to My Bookings, select the reservation, and choose 'Modify Booking'. Changes are subject to availability and may affect the total price. Any price difference will be charged or refunded accordingly.", category: "Booking", popular: true, order: 3, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f4", question: "What payment methods do you accept?", answer: "We accept all major credit cards (Visa, Mastercard, American Express), debit cards, UPI (Google Pay, PhonePe, Paytm), Net Banking (all major Indian banks), and digital wallets including PayPal, Google Pay, and Apple Pay. All payments are processed in your preferred currency.", category: "Payments", popular: true, order: 4, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f5", question: "How long does a refund take?", answer: "Refunds are typically processed within 5-7 business days after cancellation approval. The amount will be credited back to your original payment method. For UPI and card payments, refunds usually reflect within 3-5 days. Bank transfers may take 5-7 business days depending on your bank.", category: "Refunds", popular: true, order: 5, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f6", question: "How do I create an account?", answer: "Creating an account is free and takes less than a minute. Click on the 'Sign In' button in the top right corner, then select 'Create Account'. You can sign up using your email address or continue with Google or Facebook for faster registration.", category: "Account & Login", popular: true, order: 6, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f7", question: "How do I apply a coupon code?", answer: "You can apply a coupon code during the payment step of the booking process. Look for the 'Have a coupon?' section, enter your code, and click 'Apply'. The discount will be reflected in the price breakdown before you confirm payment. Only one coupon can be used per booking.", category: "Offers & Coupons", popular: true, order: 7, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f8", question: "Are hotel photos real?", answer: "Yes, all hotel photos on LuminaStay are either official property photos provided by the hotel or taken by our verified photographers. We manually review images to ensure they accurately represent the property. User-uploaded photos are marked as 'Guest Photos'.", category: "Hotels & Rooms", popular: true, order: 8, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f9", question: "Can I book for someone else?", answer: "Yes, you can book a hotel for someone else. During the booking process, you can specify the guest details separately from the payer information. The booking confirmation will be sent to both the payer and the guest's email address.", category: "Booking", popular: false, order: 9, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f10", question: "What is your cancellation policy?", answer: "Our standard cancellation policy allows free cancellation up to 48 hours before check-in. Cancellations within 48 hours may incur a one-night charge. Non-refundable bookings cannot be cancelled. Some special rates and promotional bookings may have different cancellation terms, which will be clearly displayed during booking.", category: "Cancellations", popular: false, order: 10, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f11", question: "How do I reset my password?", answer: "To reset your password, click on 'Sign In' and then select 'Forgot Password'. Enter your registered email address and we'll send you a password reset link. The link expires after 24 hours for security purposes. If you don't receive the email, check your spam folder.", category: "Account & Login", popular: false, order: 11, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f12", question: "Do you offer group discounts?", answer: "Yes, we offer special rates for group bookings of 5 rooms or more. Contact our corporate sales team at groups@luminastay.com with your requirements and we'll provide a customized quote. Group bookings may have different cancellation and payment terms.", category: "Booking", popular: false, order: 12, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f13", question: "Can I check in early?", answer: "Early check-in is subject to availability and can be requested at the time of booking or by contacting the hotel directly. Some properties offer guaranteed early check-in for an additional fee. Standard check-in time is typically 2:00 PM - 3:00 PM local time.", category: "Hotels & Rooms", popular: false, order: 13, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f14", question: "Are taxes included in the price?", answer: "Yes, all prices displayed on LuminaStay include applicable taxes and service charges unless explicitly stated otherwise. The final price breakdown during checkout will show the base rate, taxes, and any additional fees clearly.", category: "Payments", popular: false, order: 14, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f15", question: "What if I need to cancel due to an emergency?", answer: "We understand that emergencies happen. Please contact our 24/7 support team immediately at +1 (555) 123-4567 or email support@luminastay.com. We may be able to provide a partial refund or credit for future stays depending on the circumstances and at the hotel's discretion.", category: "Cancellations", popular: false, order: 15, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f16", question: "How do I contact the hotel directly?", answer: "Once your booking is confirmed, the hotel's contact information including phone number and email address will be available in your booking confirmation email and in your account under My Bookings. You can also message the hotel through our platform.", category: "Hotels & Rooms", popular: false, order: 16, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f17", question: "Can I use multiple coupons on one booking?", answer: "No, only one coupon code can be applied per booking. However, you can combine a coupon with ongoing promotional offers and loyalty points where applicable. The system will automatically apply the best available discount for you.", category: "Offers & Coupons", popular: false, order: 17, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
  { _id: "f18", question: "What is a partial refund?", answer: "A partial refund applies when only a portion of your booking amount is refundable. For example, if you cancel within the penalty period, you may receive a refund minus a one-night charge. The exact refund amount will be calculated and displayed before you confirm cancellation.", category: "Refunds", popular: false, order: 18, active: true, createdAt: "2026-01-01", updatedAt: "2026-01-01" },
];

export function getMockFAQs(filters?: { category?: string; search?: string }): FAQData[] {
  let list = [...MOCK_FAQS];
  if (filters?.category && filters.category !== "all") {
    list = list.filter((f) => f.category === filters.category);
  }
  if (filters?.search) {
    const q = filters.search.toLowerCase();
    list = list.filter((f) => f.question.toLowerCase().includes(q) || f.answer.toLowerCase().includes(q));
  }
  return list;
}
