import { DestinationData, FeaturedHotel, TravelGuide } from "@/types";

export const MOCK_DESTINATIONS: DestinationData[] = [
  {
    _id: "d1",
    city: "Dubai",
    country: "United Arab Emirates",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
    description: "Experience luxury and innovation in the city of gold, from the Burj Khalifa to desert safaris.",
    hotelCount: 342,
    startingPrice: 89,
    currency: "USD",
    category: ["luxury", "city", "family"],
    rating: 4.8,
    latitude: 25.2048,
    longitude: 55.2708,
    popular: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "d2",
    city: "Paris",
    country: "France",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
    description: "The City of Light beckons with world-class cuisine, art, and romantic ambiance.",
    hotelCount: 523,
    startingPrice: 79,
    currency: "USD",
    category: ["city", "luxury", "romance"],
    rating: 4.7,
    latitude: 48.8566,
    longitude: 2.3522,
    popular: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "d3",
    city: "Maldives",
    country: "Maldives",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80",
    description: "Crystal-clear waters, overwater bungalows, and pristine beaches await.",
    hotelCount: 156,
    startingPrice: 199,
    currency: "USD",
    category: ["beach", "luxury", "romance"],
    rating: 4.9,
    latitude: 3.2028,
    longitude: 73.2207,
    popular: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "d4",
    city: "Bali",
    country: "Indonesia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    description: "Tropical paradise with ancient temples, terraced rice paddies, and vibrant culture.",
    hotelCount: 287,
    startingPrice: 45,
    currency: "USD",
    category: ["beach", "adventure", "family"],
    rating: 4.6,
    latitude: -8.3405,
    longitude: 115.092,
    popular: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "d5",
    city: "Swiss Alps",
    country: "Switzerland",
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&q=80",
    description: "Breathtaking mountain scenery, world-class skiing, and charming alpine villages.",
    hotelCount: 198,
    startingPrice: 129,
    currency: "USD",
    category: ["mountains", "adventure", "luxury"],
    rating: 4.8,
    latitude: 46.8182,
    longitude: 8.2275,
    popular: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "d6",
    city: "Bangkok",
    country: "Thailand",
    image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&q=80",
    description: "Electric city blending ornate temples with modern skyscrapers and street food culture.",
    hotelCount: 412,
    startingPrice: 29,
    currency: "USD",
    category: ["city", "budget", "family"],
    rating: 4.4,
    latitude: 13.7563,
    longitude: 100.5018,
    popular: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "d7",
    city: "Santorini",
    country: "Greece",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80",
    description: "Iconic white-washed buildings, stunning sunsets, and crystal blue waters.",
    hotelCount: 134,
    startingPrice: 109,
    currency: "USD",
    category: ["beach", "romance", "luxury"],
    rating: 4.7,
    latitude: 36.3932,
    longitude: 25.4615,
    popular: false,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "d8",
    city: "Tokyo",
    country: "Japan",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
    description: "Where tradition meets futurism — temples, neon streets, and Michelin-star dining.",
    hotelCount: 478,
    startingPrice: 69,
    currency: "USD",
    category: ["city", "adventure", "family"],
    rating: 4.6,
    latitude: 35.6762,
    longitude: 139.6503,
    popular: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "d9",
    city: "New York",
    country: "United States",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80",
    description: "The city that never sleeps — Broadway, skyscrapers, world-class shopping and dining.",
    hotelCount: 612,
    startingPrice: 99,
    currency: "USD",
    category: ["city", "luxury", "family"],
    rating: 4.5,
    latitude: 40.7128,
    longitude: -74.006,
    popular: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "d10",
    city: "Queenstown",
    country: "New Zealand",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    description: "Adventure capital of the world with bungee jumping, skiing, and stunning lakes.",
    hotelCount: 89,
    startingPrice: 79,
    currency: "USD",
    category: ["mountains", "adventure"],
    rating: 4.7,
    latitude: -45.0312,
    longitude: 168.6626,
    popular: false,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "d11",
    city: "Marrakech",
    country: "Morocco",
    image: "https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800&q=80",
    description: "Vibrant souks, desert landscapes, and stunning riads in the heart of Morocco.",
    hotelCount: 156,
    startingPrice: 39,
    currency: "USD",
    category: ["adventure", "luxury", "city"],
    rating: 4.4,
    latitude: 31.6295,
    longitude: -7.9811,
    popular: false,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "d12",
    city: "Sydney",
    country: "Australia",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&q=80",
    description: "Harbor city with iconic Opera House, stunning beaches, and vibrant culture.",
    hotelCount: 334,
    startingPrice: 89,
    currency: "USD",
    category: ["beach", "city", "family"],
    rating: 4.6,
    latitude: -33.8688,
    longitude: 151.2093,
    popular: true,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_FEATURED_HOTELS: FeaturedHotel[] = [
  { _id: "h1", hotelId: 1, name: "Burj Al Arab", image: "https://images.unsplash.com/photo-1593431076598-6a2460dd0cc7?w=600&q=80", location: "Dubai, UAE", rating: 4.9, price: 599, currency: "USD", destinationId: "d1" },
  { _id: "h2", hotelId: 2, name: "Hotel de Paris", image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80", location: "Paris, France", rating: 4.8, price: 349, currency: "USD", destinationId: "d2" },
  { _id: "h3", hotelId: 3, name: "Conrad Maldives", image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=600&q=80", location: "Maldives", rating: 4.9, price: 499, currency: "USD", destinationId: "d3" },
  { _id: "h4", hotelId: 4, name: "Four Seasons Bali", image: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600&q=80", location: "Bali, Indonesia", rating: 4.7, price: 229, currency: "USD", destinationId: "d4" },
  { _id: "h5", hotelId: 5, name: "The Chedi Andermatt", image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80", location: "Swiss Alps", rating: 4.8, price: 389, currency: "USD", destinationId: "d5" },
  { _id: "h6", hotelId: 6, name: "Mandarin Oriental", image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600&q=80", location: "Bangkok, Thailand", rating: 4.6, price: 159, currency: "USD", destinationId: "d6" },
];

export const MOCK_TRAVEL_GUIDES: TravelGuide[] = [
  { _id: "g1", title: "10 Must-Visit Spots in Dubai", description: "From the Burj Khalifa to the Gold Souk, discover Dubai's most iconic attractions.", image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80", destinationId: "d1" },
  { _id: "g2", title: "A Weekend in Paris", description: "The perfect 3-day itinerary covering art, cuisine, and hidden gems in the City of Light.", image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=80", destinationId: "d2" },
  { _id: "g3", title: "Bali on a Budget", description: "Experience paradise without breaking the bank — affordable villas, warungs, and temple visits.", image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80", destinationId: "d4" },
  { _id: "g4", title: "Skiing in the Swiss Alps", description: "Top resorts, apres-ski spots, and alpine lodges for the ultimate winter getaway.", image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=600&q=80", destinationId: "d5" },
  { _id: "g5", title: "Tokyo's Hidden Neighborhoods", description: "Beyond Shibuya and Shinjuku — explore the charming side streets of old Tokyo.", image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=80", destinationId: "d8" },
  { _id: "g6", title: "NYC for First-Timers", description: "Your essential guide to Manhattan, Brooklyn, and everything in between.", image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=600&q=80", destinationId: "d9" },
];

export function getMockDestinations(filters?: { category?: string; popular?: boolean }): DestinationData[] {
  let list = [...MOCK_DESTINATIONS];
  const cat = filters?.category;
  if (cat && cat !== "all") {
    list = list.filter((d) => d.category.includes(cat));
  }
  if (filters?.popular) list = list.filter((d) => d.popular);
  return list;
}
