import { OfferData } from "@/types";

export const MOCK_OFFERS: OfferData[] = [
  {
    _id: "o1",
    hotelId: 1,
    hotelName: "Grand Palace Hotel",
    hotelImage: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600&q=80",
    hotelLocation: "Dubai Marina, UAE",
    rating: 4.8,
    title: "Weekend Paradise Escape",
    description: "Enjoy a luxurious weekend getaway with complimentary breakfast and spa access.",
    discountPercent: 25,
    couponCode: "WKND25",
    validUntil: new Date(Date.now() + 86400000 * 45).toISOString(),
    startingPrice: 189,
    currency: "USD",
    category: "weekend",
    featured: true,
    flashSale: false,
    seasonal: false,
    terms: ["Valid for weekend stays (Fri-Sun)", "Minimum 2 nights required", "Cannot be combined with other offers", "Subject to availability"],
    active: true,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    _id: "o2",
    hotelId: 2,
    hotelName: "Ocean View Resort",
    hotelImage: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80",
    hotelLocation: "Maldives",
    rating: 4.9,
    title: "Family Fun Package",
    description: "Bring the whole family! Kids stay free with complimentary activities and meals.",
    discountPercent: 40,
    couponCode: "FAMILY40",
    validUntil: new Date(Date.now() + 86400000 * 60).toISOString(),
    startingPrice: 249,
    currency: "USD",
    category: "family",
    featured: true,
    flashSale: false,
    seasonal: false,
    terms: ["Up to 2 children under 12 stay free", "Meal plan included for kids", "Valid for family rooms only", "Advance booking required"],
    active: true,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    _id: "o3",
    hotelId: 3,
    hotelName: "Mountain Lodge Retreat",
    hotelImage: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80",
    hotelLocation: "Swiss Alps, Switzerland",
    rating: 4.7,
    title: "Honeymoon Haven",
    description: "Romantic candlelit dinners, couple's spa treatments, and a mountain-view suite.",
    discountPercent: 30,
    couponCode: "LOVE30",
    validUntil: new Date(Date.now() + 86400000 * 90).toISOString(),
    startingPrice: 329,
    currency: "USD",
    category: "honeymoon",
    featured: true,
    flashSale: false,
    seasonal: false,
    terms: ["Valid for honeymoon suites only", "Proof of marriage may be required", "Includes complimentary champagne", "Spa reservations recommended"],
    active: true,
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    _id: "o4",
    hotelId: 4,
    hotelName: "Business Suites Tower",
    hotelImage: "https://images.unsplash.com/photo-1562778612-e1e0cda9915c?w=600&q=80",
    hotelLocation: "Singapore",
    rating: 4.6,
    title: "Corporate Travel Special",
    description: "High-speed WiFi, executive lounge access, and meeting room credits included.",
    discountPercent: 20,
    couponCode: "BIZ20",
    validUntil: new Date(Date.now() + 86400000 * 120).toISOString(),
    startingPrice: 159,
    currency: "USD",
    category: "business",
    featured: false,
    flashSale: true,
    seasonal: false,
    terms: ["Valid for weekday business stays", "Meeting room credits up to $200", "Executive lounge access included", "Early check-in available"],
    active: true,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    _id: "o5",
    hotelId: 5,
    hotelName: "The Ritz Carlton Suite",
    hotelImage: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=80",
    hotelLocation: "Paris, France",
    rating: 5.0,
    title: "Ultimate Luxury Experience",
    description: "Penthouse suite with butler service, private pool, and chauffeured city tours.",
    discountPercent: 15,
    couponCode: "LUXE15",
    validUntil: new Date(Date.now() + 86400000 * 30).toISOString(),
    startingPrice: 599,
    currency: "USD",
    category: "luxury",
    featured: true,
    flashSale: false,
    seasonal: true,
    terms: ["Limited to penthouse suites", "Butler service included", "City tours subject to availability", "Minimum 3 nights required"],
    active: true,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    _id: "o6",
    hotelId: 6,
    hotelName: "Comfort Inn Express",
    hotelImage: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&q=80",
    hotelLocation: "Bangkok, Thailand",
    rating: 4.3,
    title: "Budget Explorer Deal",
    description: "Clean, comfortable rooms at unbeatable prices. Includes free breakfast and city maps.",
    discountPercent: 50,
    couponCode: "BUDGET50",
    validUntil: new Date(Date.now() + 86400000 * 75).toISOString(),
    startingPrice: 49,
    currency: "USD",
    category: "budget",
    featured: false,
    flashSale: false,
    seasonal: false,
    terms: ["Valid for standard rooms only", "Breakfast included", "Limited-time offer", "Non-refundable"],
    active: true,
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    _id: "o7",
    hotelId: 7,
    hotelName: "Seaside Villa Resort",
    hotelImage: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&q=80",
    hotelLocation: "Bali, Indonesia",
    rating: 4.8,
    title: "Flash Sale: Beachfront Bliss",
    description: "Private villa with infinity pool. 24-hour flash sale — book now!",
    discountPercent: 55,
    couponCode: "FLASH55",
    validUntil: new Date(Date.now() + 86400000 * 1).toISOString(),
    startingPrice: 199,
    currency: "USD",
    category: "weekend",
    featured: true,
    flashSale: true,
    seasonal: false,
    terms: ["24-hour flash sale", "Non-refundable", "Valid for select villas", "Cannot be modified once booked"],
    active: true,
    createdAt: new Date(Date.now() - 86400000 * 0).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 0).toISOString(),
  },
  {
    _id: "o8",
    hotelId: 8,
    hotelName: "Desert Oasis Camp",
    hotelImage: "https://images.unsplash.com/photo-1528127269322-539801943592?w=600&q=80",
    hotelLocation: "Rajasthan, India",
    rating: 4.5,
    title: "Seasonal: Monsoon Magic",
    description: "Experience the desert come alive. Special monsoon rates with camel safari and folk dance.",
    discountPercent: 35,
    couponCode: "MONSOON35",
    validUntil: new Date(Date.now() + 86400000 * 50).toISOString(),
    startingPrice: 89,
    currency: "USD",
    category: "luxury",
    featured: false,
    flashSale: false,
    seasonal: true,
    terms: ["Valid during monsoon season only", "Camel safari included", "Weather-dependent activities", "Minimum 2 nights"],
    active: true,
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  {
    _id: "o9",
    hotelId: 9,
    hotelName: "Lake View Cottage",
    hotelImage: "https://images.unsplash.com/photo-1536524214710-1f4e3e4c8c3a?w=600&q=80",
    hotelLocation: "Lake Garda, Italy",
    rating: 4.6,
    title: "Romantic Couples Retreat",
    description: "Wine tasting, lakeside dinners, and sunset boat rides for two.",
    discountPercent: 20,
    couponCode: "COUPLE20",
    validUntil: new Date(Date.now() + 86400000 * 65).toISOString(),
    startingPrice: 219,
    currency: "USD",
    category: "honeymoon",
    featured: false,
    flashSale: false,
    seasonal: false,
    terms: ["Couples only", "Wine tasting included", "Boat ride subject to weather", "Advance reservation required"],
    active: true,
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
  },
  {
    _id: "o10",
    hotelId: 10,
    hotelName: "City Central Hotel",
    hotelImage: "https://images.unsplash.com/photo-1606402179428-a57976d71fa4?w=600&q=80",
    hotelLocation: "New York, USA",
    rating: 4.4,
    title: "Summer in the City",
    description: "Explore NYC with our summer special. Free metro cards and attraction passes included.",
    discountPercent: 30,
    couponCode: "NYC30",
    validUntil: new Date(Date.now() + 86400000 * 80).toISOString(),
    startingPrice: 139,
    currency: "USD",
    category: "budget",
    featured: false,
    flashSale: false,
    seasonal: true,
    terms: ["Valid for summer months only", "Metro card for 7 days included", "Attraction pass for 3 attractions", "Minimum 3 nights"],
    active: true,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    _id: "o11",
    hotelId: 11,
    hotelName: "Beachfront Paradise",
    hotelImage: "https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=600&q=80",
    hotelLocation: "Phuket, Thailand",
    rating: 4.7,
    title: "Family Beach Bonanza",
    description: "Water sports, kids club, and beachfront dining at incredible family rates.",
    discountPercent: 45,
    couponCode: "BEACH45",
    validUntil: new Date(Date.now() + 86400000 * 40).toISOString(),
    startingPrice: 179,
    currency: "USD",
    category: "family",
    featured: false,
    flashSale: true,
    seasonal: false,
    terms: ["Valid for family rooms", "Kids club for ages 4-12", "Water sports equipment included", "Advance booking essential"],
    active: true,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    _id: "o12",
    hotelId: 12,
    hotelName: "Hilton Downtown",
    hotelImage: "https://images.unsplash.com/photo-1590073242678-70ee3fc28f8e?w=600&q=80",
    hotelLocation: "London, UK",
    rating: 4.5,
    title: "Business Plus+ Package",
    description: "Full business center access, airport transfers, and express check-in/out.",
    discountPercent: 25,
    couponCode: "BIZPLUS25",
    validUntil: new Date(Date.now() + 86400000 * 100).toISOString(),
    startingPrice: 199,
    currency: "USD",
    category: "business",
    featured: false,
    flashSale: false,
    seasonal: false,
    terms: ["Airport transfer included", "Business center access 24/7", "Express check-in/out", "Valid for corporate bookings"],
    active: true,
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
  },
  {
    _id: "o13",
    hotelId: 13,
    hotelName: "Sunset Bay Resort",
    hotelImage: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=600&q=80",
    hotelLocation: "Goa, India",
    rating: 4.6,
    title: "Expired Offer — New Year Party",
    description: "Ring in the new year with beachside celebrations and fireworks.",
    discountPercent: 35,
    couponCode: "NY2026",
    validUntil: new Date(Date.now() - 86400000 * 30).toISOString(),
    startingPrice: 149,
    currency: "USD",
    category: "weekend",
    featured: false,
    flashSale: false,
    seasonal: true,
    terms: ["New Year package", "Non-refundable", "Minimum 3 nights", "Includes gala dinner"],
    active: false,
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 60).toISOString(),
  },
];

export function getMockOffers(filters?: { category?: string; active?: boolean }): OfferData[] {
  let list = [...MOCK_OFFERS];
  if (filters?.category && filters.category !== "all") {
    list = list.filter((o) => o.category === filters.category);
  }
  if (filters?.active !== undefined) {
    list = list.filter((o) => o.active === filters.active);
  }
  return list;
}
